### ISSUE TITLE
running locally

### ISSUE THREAD

**Issue by TomerChermesh** [eladgunders/fastapi-todos#58]
Hi, when I'm trying to run `python todos/scripts/init_db.py`

I'm getting:

```
Traceback (most recent call last):
 File “/Users/tomer/fastapi-todos/todos/scripts/init_db.py”, line 3, in <module>
  from app.core.db import create_all_entities
ModuleNotFoundError: No module named ‘app’
```

What am I doing wrong?

**Comment by eladgunders** [comment]
Hi @TomerChermesh,
run this command before initiating the db:
`export PYTHONPATH=./todos`
It is setting uop the python path for the project
